In [3]:
import numpy as np
A = np.eye(4)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
B = np.random.random((2,2,2))
print(B)

[[[0.37243633 0.62754874]
  [0.41627853 0.39358898]]

 [[0.32849784 0.77679099]
  [0.25221152 0.84952609]]]


In [5]:
C = np.random.random((9,9))
print(C.min(), C.max())

0.00015774771498155982 0.987199002037711


In [6]:
D = np.random.random(20)
print(D.mean())

0.3917204223409524


In [7]:
E = np.zeros([10,10])
E[0,:],E[-1,:],E[:,0],E[:,-1] = 1,1,1,1
print(E)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [11]:
F0 = np.ones([8,8])
F = np.zeros([F0.shape[0]+2,F0.shape[1]+2])
F[1:-1,1:-1] = F0
print(F)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [12]:
print( 0 * np.nan )  

nan


In [13]:
print( np.nan == np.nan ) 

False


In [14]:
print( np.inf > np.nan )

False


In [15]:
print( np.nan - np.nan ) 

nan


In [16]:
print( np.nan in set([np.nan]) ) 

True


In [17]:
print( 0.7 == 7 * 0.1 ) 

False


In [18]:
G = np.zeros([6,6])
i,j,k=1,0,1
while i < G.shape[0]:
    G[i,j] = k
    i+=1;j+=1;k+=1
print(G)

[[0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]]


In [19]:
H = np.zeros([6,6], dtype=int)
H[1::2,::2] = 1; H[::2,1::2] = 1
print(H)

[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


In [20]:
I = np.random.random([8,9,10])
a = 100//(7*8)
b = 100%(7*8)
print('第100个位置元素的索引:',a,b//8,b%8)
print('第100个位置元素的值 :',I[a,b//8,b%8])

第100个位置元素的索引: 1 5 4
第100个位置元素的值 : 0.5648330450010488


In [21]:
J = np.tile(np.array([[0,1],[1,0]]),(4,4))   
print(J)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [22]:
K = np.random.random([6,6])
K = (K- np.mean(K))/(np.std(K))
print(K)

[[ 1.57203799 -0.77065127  1.14830203  0.4669928   0.77316588  1.56959983]
 [-0.96355047 -0.04104779  0.90118264 -0.32974439 -1.45820966  1.50476107]
 [ 0.07416365  0.73125573 -1.28162762 -0.45386792 -1.09353913 -0.7127707 ]
 [-1.07720107 -1.5305047  -0.40921591  1.16689967  1.51766376  0.82629577]
 [-0.86670849  1.21269022 -0.81245885  0.97590966 -1.00642469 -1.50592608]
 [ 0.46030502  0.29321321  0.40989343 -0.08562417 -1.51637231  0.31111285]]


In [35]:
z=np.random.randint(10,size=(3,5))
print("z=\n",z)
print("len(z)=",len(z))
print("z.size=",z.size)
print("z.shape=",z.shape)
print(z.nbytes)

z=
 [[2 8 5 9 6]
 [1 3 8 8 0]
 [9 5 4 6 2]]
len(z)= 3
z.size= 15
z.shape= (3, 5)
60


In [36]:
M1 = np.random.random([6,3])
M2 = np.random.random([3,4])
print(np.dot(M1,M2))

[[0.21282354 0.81561826 0.72357025 0.55490095]
 [0.31857289 1.31210021 1.30199863 0.65773835]
 [0.1678057  0.46500458 0.37516156 0.44636539]
 [0.34151465 1.00296456 0.97306162 0.69672716]
 [0.20131647 0.87091342 0.75692749 0.57174469]
 [0.21288848 0.89084467 0.91802208 0.39270368]]


In [37]:
N = np.random.randint(-10,10,10)
print(N)
for i in range(len(N)):
    if i>3 and i<=8:
        k = N[i]
        N[i] = -k
print(N)

[  3  -3  -4 -10  -1   2  -5   6  -3  -4]
[  3  -3  -4 -10   1  -2   5  -6   3  -4]


In [38]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [45]:
np.array([1,1,1]) == np.array([1,1,1])

array([ True,  True,  True], dtype=bool)

array([ True,  True,  True])

In [57]:
np.array(0) / np.array(0)

<ipython-input-57-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [58]:
np.array(0) // np.array(0)

<ipython-input-58-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [59]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

In [60]:
a**a

1

In [61]:
a << a >> 2

0

In [62]:
a <- a

False

In [63]:
1j*a

1j

In [64]:
a/1/1

1.0

In [65]:
a<a>a

False

In [66]:
O = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(O)), O))

[  5.  -7.   9.  -1.  -9.   2.  -2. -10.  10. -10.]


In [67]:
P1 = np.random.randint(0,10,[3,3])
P2 = np.random.randint(0,10,[3,3])
print(P1)
print(P2)
print(np.intersect1d(P1,P2))

[[3 1 0]
 [9 8 1]
 [6 3 9]]
[[9 9 2]
 [0 5 3]
 [0 9 9]]
[0 3 9]


In [68]:
defaults = np.seterr(all='ignore')
Q = np.ones(1)/0     

In [69]:
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

In [70]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [71]:
yestaday = np.datetime64('Today','D') - np.timedelta64(1,'D')
today = np.datetime64('Today','D')
tomorrow = np.datetime64('Today','D') + np.timedelta64(1,'D')
print(yestaday)
print(today)
print(tomorrow)

2022-04-30
2022-05-01
2022-05-02


In [72]:
R = np.arange('2016-01', '2016-02', dtype='datetime64[D]')
print(R)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


In [73]:
A = np.ones([3,3])
B = 2*A
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([[-1.5, -1.5, -1.5],
       [-1.5, -1.5, -1.5],
       [-1.5, -1.5, -1.5]])

In [74]:
Z = np.random.uniform(0,10,[3,3])
print(Z)
print(Z - Z%1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))  

[[3.04880082 5.3223645  8.58929169]
 [2.66494568 2.47342821 1.5818153 ]
 [2.08080928 9.29195282 3.58590986]]
[[3. 5. 8.]
 [2. 2. 1.]
 [2. 9. 3.]]
[[3. 5. 8.]
 [2. 2. 1.]
 [2. 9. 3.]]
[[3 5 8]
 [2 2 1]
 [2 9 3]]
[[3. 5. 8.]
 [2. 2. 1.]
 [2. 9. 3.]]


In [75]:
S = np.zeros((3,3))
S += np.arange(3)
print(S)

[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]


In [76]:
def generate():
    for x in np.random.randint(0,100,9):
        yield x
T = np.fromiter(generate(),dtype=float,count=-1)  
print(T)

[23. 20.  8. 66. 17.  9. 72. 14.  3.]


In [77]:
U = np.linspace(0,1,11,endpoint=False)[1:]   
print(U)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [78]:
V = np.random.random(10)
V.sort()
print(V)

[0.1687216  0.26338403 0.28093313 0.45110893 0.67664357 0.86364002
 0.86906723 0.89546668 0.96588819 0.97190238]


In [79]:
np.add.reduce(np.arange(6))

15

In [80]:
W1 = np.random.randint(0,2,(1,2))
W2 = np.random.randint(0,2,(1,2))
print(np.allclose(W1,W2)) 

False


In [81]:
X=np.zeros(10)
X.flags.writeable=False
X.flags.writeable = True
X[0] =1

In [82]:
Z = np.random.random((5,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.78314014 0.55008503 0.98163529 0.9083099  0.57552339]
[1.00477043 1.45274314 0.7417117  1.11271227 0.56252901]


In [83]:
Z = np.random.randint(0,5,5)
Z_max_index = np.argmax(Z)              
Z[Z_max_index] = 0
print(Z)
Z = np.random.random(5)
Z[Z.argmax()] = 0                       
print(Z)

[2 1 0 1 0]
[0.         0.1377923  0.61024054 0.02230221 0.86631089]


In [84]:
Z = np.ones((5,5), [('x',float),('y',float)])                   
Z['x'],Z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))                
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [85]:
X = np.random.randint(1,10,3)
Y = np.random.randint(1,10,3)
Cauchy = 1.0 / np.subtract.outer(X, Y)     
print(Cauchy)
print(np.linalg.det(Cauchy))  

[[-0.16666667 -0.125      -0.14285714]
 [-0.33333333 -0.2        -0.25      ]
 [-0.5        -0.25       -0.33333333]]
-4.960317460317484e-05


In [86]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [87]:
np.set_printoptions(threshold=np.inf)
print(np.ones((99,99)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  

In [88]:
Z0 = np.random.randint(88)
Z = np.random.randint(1,88,10)
index = np.abs(Z-Z0).argmin()
print(Z[index])

33
